SELECT TOP (1000) [Id]
      ,[VisitScheduleId]
      ,[VisitId]
      ,[EpisodeId]
      ,[ScheduleDate]
      ,[VisitDate]
      ,[VisitBranchCode]
      ,[PatientId]
      ,[PatientNameFirst]
      ,[PatientNameLast]
      ,[WorkerId]
      ,[WorkerNameFirst]
      ,[WorkerNameLast]
      ,[ServiceCode]
      ,[VisitDiscipline]
      ,[VisitNumber]
      ,[VisitStatus]
      ,[VisitMissedReason]
      ,[Billable]
      ,[SourceSystem]
      ,[CreatedDateTime]
      ,[ModifiedDateTime]
  FROM [dbo].[dimVisit]
